version: '3.3'

services:
  postgres:
    image: postgres
    hostname: "postgres"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
  console:
    build: .
    volumes:
      - ./.env:/flask_psql_base/.env
      - ./uwsgi.ini:/flask_psql_base/uwsgi.ini
    depends_on:
      - postgres
    ports:
      - '${FLASK_RUN_PORT}:${FLASK_RUN_PORT}'
    command: bash -c "uwsgi uwsgi.ini"
